### ISSUE TITLE
Update to 1.19.4

### ISSUE THREAD

**Issue by CodeF53** [CodeF53/CardinalIceBoats#11]
```
[24/03/2023 11:56:10 AM] java.lang.NoSuchMethodError: 'net.minecraft.class_1297 net.minecraft.class_1690.method_5642()'
[24/03/2023 11:56:10 AM] 	at net.cardinalboats.Util.rotateBoat(Util.java:26)
[24/03/2023 11:56:10 AM] 	at net.cardinalboats.TurnPriming.tick(TurnPriming.java:66)
[24/03/2023 11:56:10 AM] 	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:62)
[24/03/2023 11:56:10 AM] 	at net.minecraft.class_310.handler$zed000$fabric-lifecycle-events-v1$onEndTick(class_310.java:4516)
[24/03/2023 11:56:10 AM] 	at net.minecraft.class_310.method_1574(class_310.java:1958)
[24/03/2023 11:56:10 AM] 	at net.minecraft.class_310.method_1523(class_310.java:1180)
[24/03/2023 11:56:10 AM] 	at net.minecraft.class_310.method_1514(class_310.java:801)
[24/03/2023 11:56:10 AM] 	at net.minecraft.client.main.Main.main(Main.java:237)
[24/03/2023 11:56:10 AM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
[24/03/2023 11:56:10 AM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[24/03/2023 11:56:10 AM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
crashes on priming a turn

may just need a new build because class mappings may have changed

**Comment by CodeF53** [comment]
nah
