### ISSUE TITLE
Game crashes if you leave a world while a turn is primed

### ISSUE THREAD

**Issue by CodeF53** [CodeF53/CardinalIceBoats#16]
https://github.com/CodeF53/CardinalIceBoats/assets/37855219/5d4c6124-9dfe-4a3f-9810-746b777eebcb

```
-- Head --
Thread: Render thread
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.network.ClientPlayerEntity.sendMessage(net.minecraft.text.Text, boolean)" because "player" is null
Stacktrace:
	at net.cardinalboats.Util.ClientChatLog(Util.java:44)
	at net.cardinalboats.TurnPriming.tick(TurnPriming.java:77)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.client.MinecraftClient.handler$zfb000$fabric-lifecycle-events-v1$onEndTick(MinecraftClient.java:5022)
```

**Comment by CodeF53** [comment]
Will be closed when an update containing the fix is pushed to modrinth

**Comment by CodeF53** [comment]
https://modrinth.com/mod/cardinalboats/version/1.4.0
