### ISSUE TITLE
1.21.3 support

### ISSUE THREAD

**Issue by ssterling** [CodeF53/CardinalIceBoats#20]
Mod crashes game on 1.21.3.  Relevant error is as follows:
```
[22:06:32] [main/ERROR]: Mixin apply for mod cardinalboats failed cardinalboats.mixins.json:BoatPlacementSnap from mod cardinalboats -> net.minecraft.class_1749: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyExpressionValue annotation on boatSnap could not find any targets matching 'Lnet/minecraft/class_1749;method_7836(Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;)Lnet/minecraft/class_1271;' in net/minecraft/class_1749. Using refmap cardinalboats-refmap.json [INJECT_PREPARE Applicator Phase -> cardinalboats.mixins.json:BoatPlacementSnap from mod cardinalboats -> Prepare Injections -> modifyExpressionValue$zig000$cardinalboats$boatSnap(FLnet/minecraft/class_1657;Lnet/minecraft/class_1937;)F -> Parse ->  -> Validate Targets]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyExpressionValue annotation on boatSnap could not find any targets matching 'Lnet/minecraft/class_1749;method_7836(Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;)Lnet/minecraft/class_1271;' in net/minecraft/class_1749. Using refmap cardinalboats-refmap.json [INJECT_PREPARE Applicator Phase -> cardinalboats.mixins.json:BoatPlacementSnap from mod cardinalboats -> Prepare Injections -> modifyExpressionValue$zig000$cardinalboats$boatSnap(FLnet/minecraft/class_1657;Lnet/minecraft/class_1937;)F -> Parse ->  -> Validate Targets]
	at org.spongepowered.asm.mixin.injection.selectors.TargetSelectors.validate(TargetSelectors.java:346) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:369) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:340) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:331) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at knot/com.llamalad7.mixinextras.injector.MixinExtrasInjectionInfo.<init>(MixinExtrasInjectionInfo.java:10) ~[mixinextras-0.5.0-beta.2-ea86eade6c93c3c1.jar:?]
	at knot/com.llamalad7.mixinextras.injector.MixinExtrasLateInjectionInfo.<init>(MixinExtrasLateInjectionInfo.java:15) ~[mixinextras-0.5.0-beta.2-ea86eade6c93c3c1.jar:?]
	at knot/com.llamalad7.mixinextras.injector.ModifyExpressionValueInjectionInfo.<init>(ModifyExpressionValueInjectionInfo.java:15) ~[mixinextras-0.5.0-beta.2-ea86eade6c93c3c1.jar:?]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:196) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:664) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at knot/com.llamalad7.mixinextras.sugar.impl.SugarWrapperImpl.<init>(SugarWrapperImpl.java:50) ~[mixinextras-0.5.0-beta.2-ea86eade6c93c3c1.jar:?]
	at knot/com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.<init>(WrapperInjectionInfo.java:30) ~[mixinextras-0.5.0-beta.2-ea86eade6c93c3c1.jar:?]
	at knot/com.llamalad7.mixinextras.sugar.impl.SugarWrapperInjectionInfo.<init>(SugarWrapperInjectionInfo.java:14) ~[mixinextras-0.5.0-beta.2-ea86eade6c93c3c1.jar:?]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:196) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:664) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1399) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) [?:?]
	at knot/net.minecraft.class_6089.method_9530(class_6089.java:65) [client-intermediary.jar:?]
	at knot/net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1097) [client-intermediary.jar:?]
	at knot/net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1093) [client-intermediary.jar:?]
	at knot/net.minecraft.class_4970.method_9549(class_4970.java:361) [client-intermediary.jar:?]
	at knot/net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1368) [client-intermediary.jar:?]
	at knot/net.minecraft.class_4970$class_4971.method_26200(class_4970.java:908) [client-intermediary.jar:?]
	at knot/net.minecraft.class_2246.<clinit>(class_2246.java:1311) [client-intermediary.jar:?]
	at knot/net.minecraft.class_2358.method_10199(class_2358.java:336) [client-intermediary.jar:?]
	at knot/net.minecraft.class_2966.method_12851(class_2966.java:53) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:138) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[22:06:33] [main/WARN]: Failed to get system info for GL Caps
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at knot/com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:139) ~[client-intermediary.jar:?]
	at knot/com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:134) ~[client-intermediary.jar:?]
	at knot/com.mojang.blaze3d.systems.RenderSystem.getCapsString(RenderSystem.java:478) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_6396.method_37123(class_6396.java:70) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_37274(class_310.java:2493) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_22681(class_310.java:2463) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:219) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
```

**Comment by CodeF53** [comment]
Closed by #21
